title: [Vitor Krewer]
description: [Repositório de Notas de Aula]
theme: jekyll-theme-minimal
logo: [https://pages-themes.github.io/minimal/assets/img/logo.png]
show_downloads: ["false"]
google_analytics: [Your Google Analytics tracking ID]
