title: Vitor Krewer
description: Repositório de Notas de Aula
logo: https://pages-themes.github.io/minimal/assets/img/logo.png
show_downloads: false
link: https://www.focusconcursos.com.br/professores/vitor-krewer
google_analytics: [Your Google Analytics tracking ID]
theme: jekyll-theme-minimal
