layout: home
title: Vitor Krewer
locale: pt_BR
show_downloads: false

owner:
  logo: https://pages-themes.github.io/minimal/assets/img/logo.png
  description: Repositório de Notas de Aula
  bio: This is a sample Jekyll academic website.
  linkedin: #vitorkrewer
  email: vitormkrewer@gmail.com
