title: Vitor Krewer
locale: pt_BR
description: Repositório de Notas de Aula
bio: This is a sample Jekyll academic website.
logo: https://pages-themes.github.io/minimal/assets/img/logo.png
show_downloads: false
linkedin: #vitorkrewer
email: vitormkrewer@gmail.com
